# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  pullSecrets:
    - name: ghcr-secret

persistentVolumeClaim:
  name: mysql-pvc
  storageClassName: standard
  size: 2Gi

secrets:
  mysql:
    name: mysql-secret
    key: root-password
  telegramBot:
    name: telegram-secret
    key: token

mysqlDeployment:
  image: mysql:9.0.1-oraclelinux9
  name: mysql
  replicaCount: 1
  port: 3306
  volume:
    storageName: mysql-storage
    mountPath: /var/lib/mysql

botDeployment:
  image: ghcr.io/oxidis2004/telegram-bot:main
  name: telegram-bot
  replicaCount: 1

serverDeployment:
  image: ghcr.io/oxidis2004/server:main
  name: server
  replicaCount: 1
  port: 8000
  restartPolicy: Always

serverService:
  name: server-svc
  type: LoadBalancer
  port: 8000

webDeployment:
  image: ghcr.io/oxidis2004/web:main
  name: web
  replicaCount: 1
  port: 80
  restartPolicy: Always

webService:
  name: web-svc
  type: ClusterIP
  port: 80

webIngress:
  name: web-ing
  host: nutri-system.local

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 80










#podSecurityContext: {}
  # fsGroup: 2000

#securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
#ingress:
#  enabled: false
#  className: ""
#  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
#  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
#httpRoute:
#  # HTTPRoute enabled.
#  enabled: false
#  # HTTPRoute annotations.
#  annotations: {}
#  # Which Gateways this Route is attached to.
#  parentRefs:
#  - name: gateway
#    sectionName: http
#    # namespace: default
#  # Hostnames matching HTTP header.
#  hostnames:
#  - chart-example.local
#  # List of rules and filters applied.
#  rules:
#  - matches:
#    - path:
#        type: PathPrefix
#        value: /headers
#  #   filters:
#  #   - type: RequestHeaderModifier
#  #     requestHeaderModifier:
#  #       set:
#  #       - name: My-Overwrite-Header
#  #         value: this-is-the-only-value
#  #       remove:
#  #       - User-Agent
#  # - matches:
#  #   - path:
#  #       type: PathPrefix
#  #       value: /echo
#  #     headers:
#  #     - name: version
#  #       value: v2
