apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webService.name }}
spec:
  selector:
    app: {{ .Values.webService.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.webService.port }}
      targetPort: {{ .Values.webDeployment.port }}
  type: {{ .Values.webService.type }}
