apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ${SERVER_IMAGE}
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      