version: "3.1"

services:
  db:
    image: mysql:9.0.1-oraclelinux9
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my_pass
      MYSQL_DATABASE: nutri_system
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-pmy_pass", "-e", "USE nutri_system;" ]
      interval: 7s
      timeout: 5s
      retries: 10

  server:
    depends_on:
      db:
        condition: service_healthy
    build: .
    container_name: server-cont
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: my_pass
      DB_DATABASE: nutri_system
