version: "3.1"

services:
  mysql:
    image: mysql:9.0.1-oraclelinux9
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my_pass
      MYSQL_DATABASE: nutri_system
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-pmy_pass", "-e", "USE nutri_system;" ]
      interval: 7s
      timeout: 5s
      retries: 10

  server:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ./server/Dockerfile
    container_name: server-cont
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: my_pass
      DB_DATABASE: nutri_system
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/db_health')" ]
      interval: 60s
      timeout: 3s
      retries: 2

volumes:
  mysql_data:
